on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  read-file:
    runs-on: self-hosted
    steps:
      - name: reading_file
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: ls
